- name: create ec2 instance and R53 records and update R53 records with IP's
  hosts: local
  connection: local

  tasks:
  - name: Create EC2 instance 
    amazon.aws.ec2_instance:
      name: "created by ansible"
      instance_type: t3.micro
      image_id: "ami-09c813fb71547fc4f"
      security_group: "sg-0c0e9eb837218898b"
    tags:
    name: dummy
  