- name: create ec2 instance and R53 records and update R53 records with IP's
  hosts: local
  connection: local

  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0c0e9eb837218898b # replace with your SG ID
    zone_id: "Z03050903TW06RI865LSH" # replace with your R53 zone ID
    domain_name: "daws86s.fun"

  # tasks:
  # - name: Create EC2 instance 
  #   amazon.aws.ec2_instance:
  #     name: "created by ansible"
  #     instance_type: t3.micro
  #     image_id: "ami-09c813fb71547fc4f"
  #     security_group: "sg-0c0e9eb837218898b"

  tasks:
  - name: create ec2_instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print ec2_output
  #   ansible.builtin.debug:
  #     msg: " ec2_output is {{ ec2_output }}"



    

  